# Scraping the Web Using Beautiful Soup 4

from bs4 import BeautifulSoup
from urllib.request import urlopen

# Basics from 01
url = "http://olympus.realpython.org/profiles/dionysus"
page = urlopen(url)
html = page.read().decode("utf-8")

# Create a BS4 Object on soup var
soup = BeautifulSoup(html, "html.parser")

# It is possible to unpack the Tag objects generated by this
image1, image2 = soup.find_all("img")
print(type(image2))

# Check its type
print(image1.name)

# Get the content of a Tag attribute
print(image1['src'])

# Some tags even has its own property
print(soup.title)

# It is possible to extract the string only
print(soup.title.string)